CREATE TABLE newPosts (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  content TEXT NOT NULL
)

-- 4/13: migrations are schema level
-- seed (insert) at record level
-- 1.) run migration script
-- 2.) look for 'seed' script as well
-- 3.) verify in GUI

-- test routes in Postman