CREATE TABLE replies ( id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                                                      title TEXT NOT NULL,
                                                                                 content TEXT NOT NULL)